## Урок 6. 

### Взаимосвязь величин. Параметрические и непараметрические показатели корреляции. Корреляционный анализ.

##### 1.	Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks): 
##### zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110],
##### ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832].
##### Найдите ковариацию этих двух величин с помощью элементарных действий, а затем с помощью функции cov из numpy. Найдите коэффициент корреляции Пирсона с помощью ковариации и среднеквадратичных отклонений двух признаков, а затем с использованием функций из библиотек numpy и pandas.

In [2]:
import numpy as np

In [3]:
import pandas

In [4]:
zp = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])

In [5]:
ks = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

In [6]:
cov = np.mean(zp*ks) - np.mean(zp)*np.mean(ks)
cov

9157.839999999997

In [7]:
np.cov(zp,ks, ddof=0) # смещенная ковариация

array([[ 3494.64,  9157.84],
       [ 9157.84, 30468.89]])

In [8]:
np.cov (zp,ks) # несмещенная ковариация

array([[ 3882.93333333, 10175.37777778],
       [10175.37777778, 33854.32222222]])

In [9]:
np.std(zp, ddof=1)

62.31318747531162

In [10]:
np.std(ks, ddof=1)

183.99544076477068

In [11]:
10175.37777778/(62.31318747531162*183.99544076477068)   # коэффициент корреляции Пирсона

0.88749009207411

In [12]:
cov/(np.std(zp, ddof=0)*np.std(ks, ddof=0))  # коэффициент корреляции Пирсона, подсчитанный через смещенные ковариацию и стандартное отклонение

0.8874900920739158

In [15]:
np.corrcoef(zp,ks) # через функцию в Numpy

array([[1.        , 0.88749009],
       [0.88749009, 1.        ]])

##### 2.	Измерены значения IQ выборки студентов, обучающихся в местных технических вузах: 131, 125, 115, 122, 131, 115, 107, 99, 125, 111. Известно, что в генеральной совокупности IQ распределен нормально. Найдите доверительный интервал для математического ожидания с надежностью 0.95.


In [16]:
iq = np.array([131, 125, 115, 122, 131, 115, 107, 99, 125, 111])

In [17]:
np.mean(iq) # математическое ожидание (среднее)

118.1

In [18]:
np.std(iq)

10.004498987955369

t находится из условия Ф (t)=0,95/2=0,475. Смотрим по таблице значений Ф для выборки из 10 значений: t ~ 2,26.

In [19]:
118.1 - 2.26*10.004498987955369/np.sqrt(10) # нижний предел доверительное интервала

110.95003717492182

In [20]:
118.1 + 2.26*10.004498987955369/np.sqrt(10) # верхний предел доверительное интервала

125.24996282507817

Ответ: доверительный интервал (110,95 ; 125,25) с надежностью 0.95.

##### 3.	Известно, что рост футболистов в сборной распределен нормально с дисперсией генеральной совокупности, равной 25 кв.см. Объем выборки равен 27, среднее выборочное составляет 174.2. Найдите доверительный интервал для математического ожидания с надежностью 0.95.


t находится из условия Ф (t)=0,95/2=0,475. Смотрим по таблице значений Ф для выборки из 27 значений (число степеней свободы f=n-1): t ~ 2,0555.

In [21]:
174.2 - 2.0555*5/np.sqrt(27) # нижний предел доверительное интервала

172.2220942028012

In [22]:
174.2 + 2.0555*5/np.sqrt(27) # верхний предел доверительное интервала

176.17790579719878

Ответ: доверительный интервал (172,22 ; 176,18) с надежностью 0.95.

##### 4.Выберите тему для проектной работы по курсу Теории вероятностей и математической статистики и напишите ее в комментарии к Практическому заданию. 

Статистическое сопоставление экспортно-импортных операций в мире, и в частности, в США, в ЕС и в странах БРИКС по металлам на основе https://www.kaggle.com/unitednations/global-commodity-trade-statistics
И сделать прогноз на 20___ год: какие страны с какой вероятностью экспортируют/импортируют металлы (столбцы - по видам металлов):
       '72_iron_and_steel',
       '73_articles_of_iron_or_steel', 
       '74_copper_and_articles_thereof',
       '75_nickel_and_articles_thereof',
       '76_aluminium_and_articles_thereof',
       '78_lead_and_articles_thereof', 
       '79_zinc_and_articles_thereof',
       '80_tin_and_articles_thereof',
       '81_other_base_metals_cermets_articles_thereof',
       '82_tools_implements_cutlery_etc_of_base_metal',
       '83_miscellaneous_articles_of_base_metal'.

Елена, прошу:
1) согласовать тему;
2) дать рекомендации (ссылки на методики), которые мне могут помочь "выжать" максимум из датасета.
На ваше усмотрение.

Возможно, после проведения анализа заявленного датасета, я в итоге ограничусь только "Чугуном и сталью" ("Iron_and_steel").